export enum StatusProcess {
  WAITING_CONFIGURE_DOMAIN_ENTITY = 'WAITING_CONFIGURE_DOMAIN_ENTITY',
  WAITING_CONFIGURE_PROCESS_BINDING = 'WAITING_CONFIGURE_PROCESS_BINDING',
  WAITING_PROVIDE_PROCESS_BPMN = 'WAITING_PROVIDE_PROCESS_BPMN',
  WAITING_CONFIGURE_START_FORM = 'WAITING_CONFIGURE_START_FORM',
  WAITING_CONFIGURE_USERS_TASK = 'WAITING_CONFIGURE_USERS_TASK',
  WAITING_CONFIGURE_SERVICES_TASK = 'WAITING_CONFIGURE_SERVICES_TASK',
  WAITING_GENERATE_ENTITIES = 'WAITING_GENERATE_ENTITIES',

  FINISHED = 'FINISHED',
}
